% Testing the ADMM algorithm for SDP in Matrix Completion

% Read 10-by-10 data (a low_rank matrix generated by Matlab)
% filename1 = '/Users/zhouhaobang/Desktop/Dissertation/Code/ADMM_SDP/Example/low_rank_10_B.csv';
% B = csvread(filename1);

% filename2 = '/Users/zhouhaobang/Desktop/Dissertation/Code/ADMM_SDP/Example/low_rank_10_B_new.csv';
% B_new = csvread(filename2);

% Generate a matrix
[B, B_new, rank_B] = Create_low_rank_matrix(2, 100, 0.4);    
[m_h,n_h]=size(B_new);

% Initialization
C = eye(m_h+n_h);
tol = 1e-4;
rho = m_h/50;

% Projection
P = B_new > 0;
SR = sum(sum(P))/(m_h*n_h);  % Sampling Ratio

P_new = P';
P_new = P_new(:);

% W is the recovered matrix
tic
[X, W, primal, dual, gap, iter, r_W, dinf] = ADMM_SDP(C, B_new, P, P_new, m_h, n_h, tol, rho);
toc

% The rank of the recovered matrix W
rank_W = rank(W);

% The relative error
rel_error = norm(W-B,'fro')/max(1,norm(B,'fro'));

% Plot the figures for eigenvalues 
% Before the projection
% x = 1:1:iter;
% y = Eig_B;
% y2 = zeros(iter,1);
% 
% figure
% for i = 1:iter
%     for j = 1:size(y,1)
%         plot(x(i),y(j,i),'c.')
%         hold on
%     end
% end    
% hold on
% legend('Eigenvalues')
% plot(x, y2, 'r--', 'DisplayName','Threshold')
% legend
% xlabel('Iterations')
% ylabel('Eigenvalues')
% title('The Distribution of Eigenvalues Before the Projection')
% 
% % After the projection
% x = 1:1:iter;
% y = Eig_A;
% y2 = zeros(iter,1);
% 
% figure
% for i = 1:iter
%     for j = 1:size(y,1)
%         plot(x(i),y(j,i),'c.')
%         hold on
%     end
% end    
% ylim([floor(min(min(Eig_B)))  ceil(max(max(Eig_B)))])
% hold on
% legend('Eigenvalues')
% plot(x, y2, 'r-', 'DisplayName','Threshold')
% legend
% xlabel('Iterations')
% ylabel('Eigenvalues')
% title('The Distribution of Eigenvalues After the Projection')


% Plot rank
% x = 1:1:iter;
% y = r_W;
% h = plot(x,y, 'p-', 'LineWidth',1.0,'MarkerSize',3);
% set(h,'MarkerFaceColor', get(h, 'color'));
% hold on
% ylim([0 100])
% xlabel('Iteration step k')
% ylabel('Rank of W^k')
% hold on
% o ^ d p


% Plot CPU time
% 50_CPU
% sr_3 = [0.90, 1.07, 1.57, 1.10, 1.01, 0.84, 0.89, 0.92, 0.91];
% sr_6 = [0.29, 0.32, 0.31, 0.33, 0.37, 0.38, 0.50, 0.68, 1.08];
% sr_9 = [0.17, 0.15, 0.16, 0.18, 0.183, 0.192, 0.22, 0.20, 0.21];
% 100_CPU
% sr_3 = [6.54, 7.38, 7.42, 7.88, 8.28, 9.04, 10.90, 10.65, 10.09];
% sr_6 = [3.14, 3.47, 3.74, 3.87, 4.08, 4.32, 4.36, 4.61, 4.73];
% sr_9 = [1.59, 1.72, 1.76, 1.93, 2.08, 2.19, 2.35, 2.45, 2.20];
% 
% x = 2:10;
% y1 = sr_3;
% y2 = sr_6;
% y3 = sr_9;
% h1 = plot(x,y1,'o-','LineWidth',1.0,'MarkerSize',3);
% set(h1,'MarkerFaceColor', get(h1, 'color'));
% hold on
% h2 = plot(x,y2,'^-','LineWidth',1.0,'MarkerSize',3);
% set(h2,'MarkerFaceColor', get(h2, 'color'));
% hold on
% h3 = plot(x,y3,'d-','LineWidth',1.0,'MarkerSize',3);
% set(h3,'MarkerFaceColor', get(h3, 'color'));
% hold on
% xlim([0 10])
% xlabel('Rank')
% ylabel('CPU Time')

% Plot Relative Error
% Error 50
% sr_3 = [1.62e-4, 1.2e-3, 6.6e-3, 1.62e-2, 3.86e-2, 4.22e-2, 4.62e-2, 5.19e-2, 5.31e-2];
% sr_6 = [1.12e-4, 1.39e-4, 1.42e-4, 1.24e-4, 1.54e-4, 1.61e-4, 3.8e-4, 8.2e-4, 1.4e-3];
% sr_9 = [9.16e-5, 1.02e-4, 1.11e-4, 1.08e-4, 1.19e-4, 1.27e-4, 1.31e-4, 1.54e-4, 1.18e-4];
% Error 100
% sr_3 = [1.34e-4, 1.71e-4, 1.62e-4, 1.82e-4, 2.32e-4, 1.30e-3, 4.10e-3];
% sr_6 = [1.04e-4, 1.16e-4, 1.22e-4, 1.32e-4, 1.47e-4, 1.39e-4, 1.46e-4];
% sr_9 = [0.89e-4, 0.83e-4, 0.95e-4, 0.85e-4, 0.92e-4, 1.03e-4, 1.05e-4];

% y1 = [1.34, 1.71, 1.62, 1.82, 2.32, 13, 41];
% y2 = [1.04, 1.16, 1.22, 1.32, 1.47, 1.39, 1.46];
% y3 = [0.89, 0.83, 0.95, 0.85, 0.92, 1.03, 1.05];

% y1 = [1.62e-4, 1.2e-3, 6.6e-3, 1.62e-2, 3.86e-2, 4.22e-2, 4.62e-2, 5.19e-2, 5.31e-2];
% y2 = [1.12e-4, 1.39e-4, 1.42e-4, 1.24e-4, 1.54e-4, 1.61e-4, 3.8e-4, 8.2e-4, 1.4e-3];
% y3 = [9.16e-5, 1.02e-4, 1.11e-4, 1.08e-4, 1.19e-4, 1.27e-4, 1.31e-4, 1.54e-4, 1.18e-4];

% y1 = [0.000162, 0.0012, 0.0066, 0.0162];
% y2 = [0.000112, 0.000139, 0.000142, 0.000124];
% y3 = [0.0000916, 0.000102, 0.000111, 0.000108];

% y1 = [0.000134, 0.000171, 0.000162, 0.000182, 0.000232, 0.0013, 0.0041];
% y2 = [0.000104, 0.000116, 0.000122, 0.000132, 0.000147, 0.000139, 0.000146];
% y3 = [0.000089, 0.000083, 0.000095, 0.000085, 0.000092, 0.000103, 0.000105];

% x = 2:5;
% h1 = plot(x,log(y1),'o-','LineWidth',1.0,'MarkerSize',3);
% set(h1,'MarkerFaceColor', get(h1, 'color'));
% hold on
% h2 = plot(x,log(y2),'^-','LineWidth',1.0,'MarkerSize',3);
% set(h2,'MarkerFaceColor', get(h2, 'color'));
% hold on
% h3 = plot(x,log(y3),'d-','LineWidth',1.0,'MarkerSize',3);
% set(h3,'MarkerFaceColor', get(h3, 'color'));
% hold on
% xlim([0 8])
% ylim()
% xlabel('Rank')
% ylabel('Relative Error')

% Plot the condtion number
% x = 1:iter;
% y = log(con);
% plot(x,y)
% xlabel('Iertation step k')
% ylabel('Cond(LL^T)')
% hold on

% Plot violation
% x = 1:iter;
% y = dinf;
% h = plot(x,y, '-', 'LineWidth',1.0,'MarkerSize',3);
% set(h,'MarkerFaceColor', get(h, 'color'));
% xlabel('Iteration step k')
% ylabel('Violation')
% hold on